/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.prototypevirtualid.view;

/**
 *
 * @author BryanPC
 */
public class FrmMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainMenu
     */
    public FrmMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuRequestId = new javax.swing.JMenuItem();
        mnuUpdateStudnt = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuStudentDelete = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuAttention = new javax.swing.JMenu();
        menuInmediateAttention = new javax.swing.JMenuItem();
        mnuMakeAppo = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnuAddDoctor = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Student");

        mnuRequestId.setText("RequestID");
        mnuRequestId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRequestIdActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRequestId);

        mnuUpdateStudnt.setText("Update Data");
        mnuUpdateStudnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUpdateStudntActionPerformed(evt);
            }
        });
        jMenu1.add(mnuUpdateStudnt);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Director");

        mnuStudentDelete.setText("Delete Student");
        mnuStudentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStudentDeleteActionPerformed(evt);
            }
        });
        jMenu2.add(mnuStudentDelete);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Polyclinic");

        mnuAttention.setText("Attention");

        menuInmediateAttention.setText("Inmediate Attention");
        menuInmediateAttention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInmediateAttentionActionPerformed(evt);
            }
        });
        mnuAttention.add(menuInmediateAttention);

        mnuMakeAppo.setText("Make Appointment");
        mnuAttention.add(mnuMakeAppo);

        jMenu5.add(mnuAttention);

        jMenu7.setText("Doctor");

        mnuAddDoctor.setText("Add New Doctor");
        mnuAddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddDoctorActionPerformed(evt);
            }
        });
        jMenu7.add(mnuAddDoctor);

        jMenu5.add(jMenu7);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRequestIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRequestIdActionPerformed
        FrmStudentRecord frmStudent = new FrmStudentRecord();
        this.setVisible(false);
        frmStudent.setVisible(true);
    }//GEN-LAST:event_mnuRequestIdActionPerformed

    private void mnuStudentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStudentDeleteActionPerformed
        FrmStudentDelete frmstudentdelete = new FrmStudentDelete();
        this.setVisible(false);
        frmstudentdelete.setVisible(true);
    }//GEN-LAST:event_mnuStudentDeleteActionPerformed

    private void menuInmediateAttentionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInmediateAttentionActionPerformed
        FrmDiagnosisRecord inmediate = new FrmDiagnosisRecord();
        this.setVisible(false);
        inmediate.setVisible(true);
    }//GEN-LAST:event_menuInmediateAttentionActionPerformed

    private void mnuAddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddDoctorActionPerformed
        FrmDoctorRecord doctor = new FrmDoctorRecord();
        this.setVisible(false);
        doctor.setVisible(true);
    }//GEN-LAST:event_mnuAddDoctorActionPerformed

    private void mnuUpdateStudntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUpdateStudntActionPerformed
        FrmUpdateStudent update = new FrmUpdateStudent();
        this.setVisible(false);
        update.setVisible(true);
    }//GEN-LAST:event_mnuUpdateStudntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuInmediateAttention;
    private javax.swing.JMenuItem mnuAddDoctor;
    private javax.swing.JMenu mnuAttention;
    private javax.swing.JMenuItem mnuMakeAppo;
    private javax.swing.JMenuItem mnuRequestId;
    private javax.swing.JMenuItem mnuStudentDelete;
    private javax.swing.JMenuItem mnuUpdateStudnt;
    // End of variables declaration//GEN-END:variables
}
